//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClientNovaPoshta.ServiceReferencePoshta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePoshta.INovaPoshta")]
    public interface INovaPoshta {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INovaPoshta/CreatePackage")]
        void CreatePackage(WCF_Lib.Package package);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INovaPoshta/CreatePackage")]
        System.Threading.Tasks.Task CreatePackageAsync(WCF_Lib.Package package);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INovaPoshtaChannel : WpfClientNovaPoshta.ServiceReferencePoshta.INovaPoshta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NovaPoshtaClient : System.ServiceModel.ClientBase<WpfClientNovaPoshta.ServiceReferencePoshta.INovaPoshta>, WpfClientNovaPoshta.ServiceReferencePoshta.INovaPoshta {
        
        public NovaPoshtaClient() {
        }
        
        public NovaPoshtaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NovaPoshtaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NovaPoshtaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NovaPoshtaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreatePackage(WCF_Lib.Package package) {
            base.Channel.CreatePackage(package);
        }
        
        public System.Threading.Tasks.Task CreatePackageAsync(WCF_Lib.Package package) {
            return base.Channel.CreatePackageAsync(package);
        }
    }
}
